spring.application.name=blood-donor-management
spring.datasource.url=jdbc:mysql://localhost:3306/bdms?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.springframework.security=DEBUG
